name: Kind Mode DPU Offload

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: kind-dpu-offload-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kind-dpu-offload:
    uses: ./.github/workflows/kind-tft.yml
